# -*- coding: utf-8 -*-
"""NLP_Task3_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6H5-htQf6uRffHpkvcRGX9ZzJSpRti5

# NLP Assignment - 3: Chatbot using Transformers

---

**Objective:** Build a conversational chatbot using a pre-trained transformer model from Hugging Face that can interact with users and generate meaningful responses.

**Model Used:** `microsoft/DialoGPT-medium` - a dialogue-focused model trained specifically for multi-turn conversations.

**Pipeline Flow:**
User Input -> Model Processing -> Response Generation -> Display Output -> Loop Until Exit

---
## Step 1: Install Required Libraries
"""

# Install Hugging Face transformers library and PyTorch backend
!pip install transformers torch --quiet

"""---
## Step 2: Import Libraries

- `AutoTokenizer` - converts human text into numbers the model can understand
- `AutoModelForCausalLM` - the transformer model that generates text responses
- `torch` - PyTorch, used as the computation engine behind the model
"""

# Importing tokenizer and model classes from Hugging Face transformers
from transformers import AutoTokenizer, AutoModelForCausalLM

# PyTorch is used as the backend for all model computations
import torch

print("Libraries imported successfully!")

"""---
## Step 3: Load the Pre-trained Transformer Model

"""

# We are using DialoGPT-medium - it is specifically fine-tuned for conversations
# This makes it much better at dialogue compared to the base GPT-2 model
MODEL_NAME = "microsoft/DialoGPT-medium"

print(f"Loading model: {MODEL_NAME}")
print("Please wait - model is being downloaded for the first time...")

# Load the tokenizer - handles converting text to token IDs and back
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Load the pre-trained model weights from Hugging Face
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Set the model to evaluation mode since we are only generating, not training
model.eval()

print("\nModel loaded successfully! DialoGPT-medium is ready.")

"""---
## Step 4: Define the Response Generation Function

This function handles everything needed to produce a chatbot reply:
1. Encodes the user message into token IDs
2. Appends it to the conversation history so the model remembers context
3. Runs the model to generate a response
4. Decodes the output back into readable text
"""

def generate_response(user_message, conversation_history):

    new_input_ids = tokenizer.encode(
        user_message + tokenizer.eos_token,
        return_tensors="pt"
    )

    if conversation_history is not None:
        bot_input_ids = torch.cat([conversation_history, new_input_ids], dim=-1)
    else:
        bot_input_ids = new_input_ids

    chat_history_ids = model.generate(
        bot_input_ids,
        max_length=1000,
        pad_token_id=tokenizer.eos_token_id,
        no_repeat_ngram_size=3,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.75
    )


    reply = tokenizer.decode(
        chat_history_ids[:, bot_input_ids.shape[-1]:][0],
        skip_special_tokens=True
    )

    return reply, chat_history_ids


print("Response generation function defined successfully!")

"""---
## Step 5: Run the Chatbot

The chatbot will:
- Print a greeting message
- Wait for you to type a message
- Generate and display a response
- Keep looping until you type `exit` or `quit`

"""

def run_chatbot():

    conversation_history = None

    # Print the chatbot header and opening greeting
    print("=" * 55)
    print("   Chatbot using Transformers (DialoGPT-medium)")
    print("=" * 55)
    print("Chatbot: Hello! I am your AI assistant. How can I help you today?")
    print("-" * 55)
    print("  Type 'exit' or 'quit' to end the conversation.")
    print("-" * 55)

    # Keep the chatbot running in a loop until exit condition is met
    while True:

        user_input = input("\nYou: ").strip()

        if not user_input:
            print("Chatbot: Please type something so I can help you!")
            continue

        if user_input.lower() in ["exit", "quit"]:
            print("\nChatbot: It was great talking to you! Goodbye!")
            print("=" * 55)
            break

        response, conversation_history = generate_response(user_input, conversation_history)

        print(f"\nChatbot: {response}")


# Start the chatbot
run_chatbot()